name: "Build back"

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  build-back-artefact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build backend
        run: pnpm back build ${{ inputs.tag }}
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: back-build-${{ inputs.tag }}
          path: back/back-build.tar.gz
