name: Discord Notification

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
        description: The version tag
      environment:
        type: string
        description: Environment to send notification to. Will change the discord chanel to notify.
        required: true
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true

jobs:
  send-notification:
    name: Send Discord notification
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "content": "La ${{ inputs.tag }} est deployée en ${{ inputs.environment }}",
            "embeds": [
              {
                "title": "Liens utiles :",
                "fields": [
                  {
                    "name": "Changelog :",
                    "value": "https://www.notion.so/gip-inclusion/Journal-des-modifications-3831ee7ed3ba48e6bd29aac47c0a7f78"
                  },
                  {
                    "name": "Application :",
                    "value": "https://${{ inputs.environment }}.immersion-facile.beta.gouv.fr"
                  },
                  {
                    "name": "Pour passer au prochain environnement, validez ici",
                    "value": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
