name: Tag version

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  tag-version:
    name: Tag version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a "${{ inputs.tag }}" -m "Deployment tag"
          git push --tags
