name: "Dev - Build front, back and deploy"

on:
  push:
    branches:
      - dev

jobs:
  validation:
    uses: ./.github/workflows/fullcheck.yml

  build-front-artefact:
    uses: ./.github/workflows/build-front-artefact.yml

  build-back-artefact:
    uses: ./.github/workflows/build-back-artefact.yml

  deploy-dev:
    environment: dev
    needs: [validation, build-front-artefact, build-back-artefact]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      envType: "dev"
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
