name: "Staging - Build front, back and deploy"

on:
  push:
    branches:
      - staging

jobs:
  build-front-artefact:
    uses: ./.github/workflows/build-front-artefact.yml

  build-back-artefact:
    uses: ./.github/workflows/build-back-artefact.yml

  deploy-staging:
    needs: [build-front-artefact, build-back-artefact]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      environment: staging
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
