name: "Continuous Deployment"

on:
  push:
    branches:
      - main

jobs:
  validation:
    uses: ./.github/workflows/fullcheck.yml
    secrets:
      API_KEY_OPEN_CAGE_DATA_GEOCODING: ${{ secrets.API_KEY_OPEN_CAGE_DATA_GEOCODING }}
      API_KEY_OPEN_CAGE_DATA_GEOSEARCH: ${{ secrets.API_KEY_OPEN_CAGE_DATA_GEOSEARCH }}
      SIRENE_BEARER_TOKEN: ${{ secrets.SIRENE_BEARER_TOKEN }}

  build-front-artefact:
    uses: ./.github/workflows/build-front-artefact.yml
    with:
      tag: "v${{ github.run_number }}"
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  build-back-artefact:
    uses: ./.github/workflows/build-back-artefact.yml
    with:
      tag: "v${{ github.run_number }}"

  tag:
    name: "Tag"
    uses: ./.github/workflows/ci-add-tag.yml
    with:
      tag: "v${{ github.run_number }}"

  deploy-dev:
    name: Deploy dev
    needs: [ validation, tag, build-front-artefact, build-back-artefact ]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      environment: dev
      tag: "v${{ github.run_number }}"
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  run-playwright-on-dev:
    name: Run Playwright on dev
    needs: deploy-dev
    uses: ./.github/workflows/playwright-run.yml
    with:
      environment: dev
      tag: "v${{ github.run_number }}"
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}

  deploy-staging:
    name: Deploy staging
    needs: deploy-dev
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      environment: staging
      tag: "v${{ github.run_number }}"
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  deploy-prod:
    name: Deploy prod
    needs: deploy-staging
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      environment: prod
      tag: "v${{ github.run_number }}"
      region: "osc-secnum-fr1"
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  create-release-notes:
    name: Create release notes
    needs: deploy-prod
    uses: ./.github/workflows/create-release-notes.yml
    with:
      tag: "v${{ github.run_number }}"
      repository: ${{ github.repository }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}