name: Run Cypress on dev
on:
  workflow_call:
    secrets:
      CYPRESS_RECORD_KEY:
        required: true
      DISCORD_WEBHOOK_URL:
        required: true
    inputs:
      tag:
        type: string
        required: true
      environment:
        type: string
        required: true
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Send Discord notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "content": "Les tests Cypress sont lancés, le report est dispo sur : https://cloud.cypress.io/projects/vctxdm/runs",
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Cypress run
        continue-on-error: true
        run: |
          pnpm cypress run-e2e \
            --key ${{ secrets.CYPRESS_RECORD_KEY }} \
            --tag "dev,${{ inputs.tag }}" \
            --parallel \
            --ci-build-id ${{ inputs.tag }} \
            --browser chrome \
            --headless \
            --quiet \
