name: "Backup DB scalingo & copy to clever"
#on:
#  schedule:
#    - cron: ""
on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2
      # - name: Install scalingo CLI
      #   run: |
      #     wget -qO- https://cli-dl.scalingo.com/install.sh | bash
      #     echo "$HOME/bin" >> $GITHUB_PATH
      # - name: Login to scalingo
      #   run: scalingo login --api-token ${{ secrets.SCALINGO_API_TOKEN }}
      # - name: Backup DB
      #   run: scalingo --app ${{ secrets.SCALINGO_APP }} --region ${{ secrets.SCALINGO_REGION }} --addon ${{ secrets.SCALINGO_DB_ADDON_ID }} backups-download
      # - name: Upload backup to clever
      #
      - name: Install AWS CLI
        # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          aws --version
      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.CELLAR_ADDON_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.CELLAR_ADDON_KEY_SECRET }}
      #     aws-region: us-east-2
      # - name: Copy files to the production website with the AWS CLI
      #   run: |
      #     aws s3 list-objects --endpoint-url https://cellar-c2.services.clever-cloud.com --bucket immersion-dev
        #run: |
        #  aws s3 put-object --endpoint-url https://cellar-c2.services.clever-cloud.com --bucket immersion-dev --key cats.png --body ../cats.png --content-type image/png
      
