name: "Generic workflow to deploy to scalingo, given arguments"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
      region:
        required: false
        type: string
        default: "osc-fr1"
    secrets:
      SCALINGO_API_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Install scalingo CLI
        run: |
          wget -qO- https://cli-dl.scalingo.com/install.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Download back artefact
        uses: actions/download-artifact@v3
        with:
          name: back-build-${{github.sha}}
      - name: Download front artefact
        uses: actions/download-artifact@v3
        with:
          name: front-build-${{github.sha}}
      - name: Login to scalingo
        run: scalingo login --api-token ${{ secrets.SCALINGO_API_TOKEN }}
      - name: Deploy back
        run: scalingo --app if-${{ inputs.environment }}-back --region ${{ inputs.region }} deploy back-build.tar.gz
      - name: Deploy front
        run: scalingo --app if-${{ inputs.environment }}-front --region ${{ inputs.region }} deploy front-build.tar.gz
