name: "Generic workflow to deploy to scalingo, given arguments"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      tag:
        type: string
        required: true
      region:
        required: false
        type: string
        default: "osc-fr1"
    secrets:
      SCALINGO_API_TOKEN:
        required: true
      DISCORD_WEBHOOK_URL:
        required: true

jobs:
  deploy:
    name: "Deploy to ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency:
      group: deploy-to-scalingo-${{ inputs.environment }}
      cancel-in-progress: true
    steps:
      - name: Install scalingo CLI
        run: |
          wget -qO- https://cli-dl.scalingo.com/install.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Download back artefact
        uses: actions/download-artifact@v3
        with:
          name: back-build-${{ inputs.tag }}
      - name: Download front artefact
        uses: actions/download-artifact@v3
        with:
          name: front-build-${{ inputs.tag }}
      - name: Login to scalingo
        run: scalingo login --api-token ${{ secrets.SCALINGO_API_TOKEN }}
      - name: Deploy back
        run: scalingo --app if-${{ inputs.environment }}-back --region ${{ inputs.region }} deploy back-build.tar.gz ${{ inputs.tag }}
      - name: Deploy front
        run: scalingo --app if-${{ inputs.environment }}-front --region ${{ inputs.region }} deploy front-build.tar.gz ${{ inputs.tag }}
      - name: Send Discord notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "content": "La ${{ inputs.tag }} est deployée en ${{ inputs.environment }}",
            "embeds": [
              {
                "title": "Liens utiles :",
                "fields": [
                  {
                    "name": "Changelog :",
                    "value": "https://www.notion.so/gip-inclusion/Journal-des-modifications-3831ee7ed3ba48e6bd29aac47c0a7f78"
                  },
                  {
                    "name": "Application :",
                    "value": "https://${{ inputs.environment }}.immersion-facile.beta.gouv.fr"
                  },
                  {
                    "name": "Pour passer au prochain environnement, validez ici",
                    "value": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
