name: "Fullcheck of the project + integration tests"

on:
  workflow_call:

jobs:
  validation:
    name: ""
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        command:
          ["pnpm fast-checks", "pnpm typecheck", "pnpm back test", "pnpm lint"]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: ${{matrix.command}}
        env:
          COMMAND: ${{matrix.command}}
        run: |
          STORAGE_FULL_PATH=$(pwd)/back/storage
          mkdir -p $STORAGE_FULL_PATH/tmp/     
          STORAGE_ROOT=$STORAGE_FULL_PATH $COMMAND

  back-integration-tests:
    name: "Back integration tests"
    runs-on: ubuntu-latest
    env:
      TEST_DATABASE_URL: postgresql://immersion:password@localhost:5432/immersion-db
    services:
      postgres:
        image: postgis/postgis:13-master
        env:
          POSTGRES_USER: immersion
          POSTGRES_PASSWORD: password
          POSTGRES_DB: immersion-db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run migrations
        run: NODE_ENV=test DATABASE_URL=$TEST_DATABASE_URL pnpm back db:up
      - name: Run integration tests
        run: |
          echo $TEST_DATABASE_URL
          STORAGE_FULL_PATH=$(pwd)/back/storage
          mkdir -p $STORAGE_FULL_PATH/tmp/ 
          DATABASE_URL=$TEST_DATABASE_URL STORAGE_ROOT=$STORAGE_FULL_PATH pnpm back test:integration
