name: Run Playwright on dev
on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true
    inputs:
      tag:
        type: string
        required: true
      environment:
        type: string
        required: true
jobs:
  playwright-run:
    name: Playwright run
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Send Discord notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "content": "Les tests Playwright sont lancés, le report est dispo dans les logs de l’action Github"
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Playwright run
        run: pnpm playwright test:ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
