name: Run Playwright on dev
on:
  workflow_call:
    secrets:
      SCALINGO_API_TOKEN:
        required: true
    inputs:
      tag:
        type: string
        required: true
      environment:
        type: string
        required: true
jobs:
  playwright-run:
    name: Playwright run
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Install scalingo CLI
        run: |
          wget -qO- https://cli-dl.scalingo.com/install.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Login to scalingo
        run: scalingo login --api-token ${{ secrets.SCALINGO_API_TOKEN }}
      - name: Run DB seed
        run: scalingo --app if-dev-back run pnpm db:seed
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Playwright run
        run: pnpm playwright test:ci
