name: "Destroy review apps"

on:
  pull_request:
    types: [ closed ]

concurrency:
  group: review-app-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  destroy-review-apps:
    runs-on: ubuntu-latest
    environment: review-app
    steps:
      - name: Install scalingo CLI
        run: |
          wget -qO- https://cli-dl.scalingo.com/install.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Login to scalingo
        run: scalingo login --api-token ${{ secrets.SCALINGO_API_TOKEN }}
      - name: Destroy review apps
        run: |
          scalingo --app if-dev-front-pr${{ github.event.number }} destroy --force
          scalingo --app if-dev-back-pr${{ github.event.number }} destroy --force
